### ISSUE TITLE
external-world крашится после внедрения cache

### ISSUE THREAD

**Issue by notarseniy** [straykov/initium#34]
@MacB ➜  initium git:(master) ✗ gulp external-world
[05:25:20] Using gulpfile ~/Documents/DEV/Codelnaya/initium/gulpfile.js
[05:25:20] Starting 'external-world'...
[05:25:20] Starting 'pug'...
[05:25:20] Finished 'pug' after 11 ms
[05:25:20] Starting 'styles'...
[05:25:20] Finished 'styles' after 3.68 ms
[05:25:20] Starting 'scripts'...
[05:25:20] Finished 'scripts' after 12 ms
[05:25:20] Starting 'img'...
[05:25:20] Finished 'img' after 4.96 ms
[05:25:20] Starting 'cache'...
[05:25:20] Finished 'cache' after 3.75 ms
[05:25:20] Starting 'watch'...
[05:25:20] Finished 'watch' after 25 ms
[05:25:20] Starting 'web-server'...
[05:25:20] Finished 'web-server' after 4.28 ms
[05:25:20] Finished 'external-world' after 69 ms
[05:25:21] Starting 'cache'...
[05:25:21] Finished 'cache' after 2.14 ms
[05:25:21] gulp-imagemin: ✔ logo.jpg (already optimized)
[05:25:21] gulp-imagemin: Minified 1 image (saved 0 B - 0%)
/Users/Kern0/Documents/DEV/Codelnaya/initium/node_modules/browser-sync/lib/browser-sync.js:671
        bs.io.sockets.emit("browser:reload");
             ^

TypeError: Cannot read property 'sockets' of undefined
    at BrowserSync.doFileReload (/Users/Kern0/Documents/DEV/Codelnaya/initium/node_modules/browser-sync/lib/browser-sync.js:671:14)
    at EventEmitter.file:reload (/Users/Kern0/Documents/DEV/Codelnaya/initium/node_modules/browser-sync/lib/internal-events.js:20:16)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at Object.changedFile (/Users/Kern0/Documents/DEV/Codelnaya/initium/node_modules/browser-sync/lib/file-utils.js:26:27)
    at EventEmitter.file:changed (/Users/Kern0/Documents/DEV/Codelnaya/initium/node_modules/browser-sync/lib/internal-events.js:13:23)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Object.emitChangeEvent (/Users/Kern0/Documents/DEV/Codelnaya/initium/node_modules/browser-sync/lib/public/public-utils.js:13:17)
    at Transform.reload._transform (/Users/Kern0/Documents/DEV/Codelnaya/initium/node_modules/browser-sync/lib/public/stream.js:70:31)

**Comment by notarseniy** [comment]
@straykov /cc

**Comment by straykov** [comment]
Убрали external-world вообще
